// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TfsUndoAndDeleteNewFilesExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "TfsUndoAndDeleteNewFilesExtension.dc12e21c-f5a9-4d77-b5f7-4d8642858c42";
        public const string Name = "TfsUndoAndDeleteNewFilesExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Denys Belik";
        public const string Tags = "";
    }
}
