// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TfsUndoAndDeleteNewFilesExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TfsUndoAndDeleteNewFilesExtensionString = "21bf7b15-9ee3-4774-bb51-5b0a8a3b76ea";
        public static Guid TfsUndoAndDeleteNewFilesExtension = new Guid(TfsUndoAndDeleteNewFilesExtensionString);

        public const string guidHatPackageGrpSetString = "4f23bc3a-c823-4632-8a73-3bb5ad25fd5b";
        public static Guid guidHatPackageGrpSet = new Guid(guidHatPackageGrpSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int UndoAndDeleteNewFilesCommand = 0x0100;
        public const int igrpPendingChangesPageUndoIncludedChanges = 0x2035;
        public const int igrpPendingChangesPageUndoExcludedChanges = 0x2036;
    }
}